pub const TILESET_TERRAIN_ROWS: usize = 1;
pub const TILESET_TERRAIN_COLUMNS: usize = 4;
pub const TILESET_TERRAIN_IDX_GRASS: usize = 0;
pub const TILESET_TERRAIN_IDX_GRASS_WITH_FLOWER: usize = 1;
pub const TILESET_TERRAIN_IDX_GRASS_WITH_STONE: usize = 2;
pub const TILESET_TERRAIN_IDX_SIGNPOST: usize = 3;
